name: Security Log Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  log-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run monitoring script
        run: python monitor_logs.py
          git config --local user.name "GitHub Action"
          git add security_log.txt
          git commit -am "Update security logs" || echo "No changes to commit"
          git push
